### ISSUE TITLE
No code suggests on "this" in vue methods and fetch method

### ISSUE THREAD

**Issue by scjmjy** [Goopil/nest-nuxt-starter#439]
Hi, this is a awesome project for combining nestjs and nuxtjs.
And I encountered a problem that I cann't get code suggests on "this" in vue methods and fetch method,
But it works a bit well in vue data method.

![a00fb601e4ce60d8f298a4dced575f1](https://user-images.githubusercontent.com/3145541/133014393-56221026-fa52-4655-b448-c12ca9d8f8b0.png)

**Comment by Goopil** [comment]
Hello, 

Thanks for the issue.
look Like a type is missing.

I will have a look.

**Comment by Goopil** [comment]
Should be fixed.
Fill free to reopen this issue if it doesn't work for you.

**Comment by scjmjy** [comment]
@Goopil 
Well done 👍
It works when using "class-style" vue component with "nuxt-property-decorator".
Thanks!

**Comment by scjmjy** [comment]
@Goopil 
Hello again~
While types have been fixed when using "class-style" vue component with "nuxt-property-decorator",
but it still not work when using normal-style vue component.
I tried to fix it, but still need your help 😊

![1631765477(1)](https://user-images.githubusercontent.com/3145541/133548633-f94f57e8-5a12-404f-a0fb-6212681ac8d6.png)

**Comment by Goopil** [comment]
Strange, it work on my side ?

do you have some code to share ?

@scjmjy

**Comment by Goopil** [comment]
Feel free to reopen
